package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"html"
	"log"
	"net/http"
	"net/mail"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"tradegravity/internal/emaildelivery"
	"tradegravity/internal/subscriptions"
)

const (
	secretEnvironment        = "TRADEGRAVITY_UNSUBSCRIBE_SECRET"
	webhookSecretEnvironment = "RESEND_WEBHOOK_SECRET"
	resendAPIKeyEnvironment  = "RESEND_API_KEY"
)

type resendConfirmationSender struct {
	provider      *emaildelivery.ResendProvider
	from, replyTo string
}

func (sender resendConfirmationSender) SendConfirmation(ctx context.Context, confirmation subscriptions.ConfirmationEmail) (string, error) {
	safeURL := html.EscapeString(confirmation.ConfirmationURL)
	message := emaildelivery.Message{
		From: sender.from, ReplyTo: sender.replyTo, To: confirmation.To,
		Subject: "Confirm your TradeGravity briefing subscription",
		HTML:    `<!doctype html><html><body><p>You requested the TradeGravity research briefing.</p><p><a href="` + safeURL + `">Review and confirm your subscription</a></p><p>Opening the link does not subscribe you; use the confirmation button on that page. This link expires soon. If you did not request it, ignore this email.</p></body></html>`,
		Text:    "You requested the TradeGravity research briefing.\n\nReview and confirm your subscription:\n" + confirmation.ConfirmationURL + "\n\nOpening the link does not subscribe you; use the confirmation button on that page. This link expires soon. If you did not request it, ignore this email.\n",
	}
	return sender.provider.Send(ctx, message, confirmation.IdempotencyKey)
}

func main() {
	databasePath := flag.String("db", "", "private SQLite subscription database path")
	publicBaseURL := flag.String("base-url", "", "public HTTPS base URL for links generated by the registry")
	listenAddress := flag.String("listen", "127.0.0.1:8081", "HTTP listen address; use a TLS reverse proxy for public service")
	enableResendWebhook := flag.Bool("enable-resend-webhook", false, "enable the signed Resend feedback endpoint")
	enableSignup := flag.Bool("enable-signup", false, "enable the public double-opt-in subscription form")
	signupAudience := flag.String("signup-audience", "tradegravity-briefing", "fixed audience for the public form")
	consentSource := flag.String("consent-source", "public-subscribe-form", "consent evidence source label")
	privacyVersion := flag.String("privacy-notice-version", "v1", "privacy notice version recorded with consent")
	privacyURL := flag.String("privacy-notice-url", "", "public HTTPS privacy notice URL")
	confirmationFrom := flag.String("confirmation-from", "", "verified sender used for confirmation mail")
	confirmationReplyTo := flag.String("confirmation-reply-to", "", "optional reply-to address")
	confirmationTTL := flag.Duration("confirmation-ttl", 30*time.Minute, "confirmation link lifetime (5m to 24h)")
	maximumPending := flag.Int("max-pending", 100, "maximum unexpired pending confirmations")
	flag.Parse()

	secret := []byte(os.Getenv(secretEnvironment))
	if len(secret) == 0 {
		fatal(fmt.Errorf("%s is required", secretEnvironment))
	}
	registry, err := subscriptions.Open(*databasePath, secret, *publicBaseURL)
	if err != nil {
		fatal(err)
	}
	defer registry.Close()

	options := subscriptions.HandlerOptions{Now: time.Now}
	if *enableResendWebhook {
		webhookSecret := os.Getenv(webhookSecretEnvironment)
		if strings.TrimSpace(webhookSecret) == "" {
			fatal(fmt.Errorf("%s is required when the Resend webhook is enabled", webhookSecretEnvironment))
		}
		options.ResendWebhookSecret = webhookSecret
	}
	if *enableSignup {
		provider, providerErr := emaildelivery.NewResendProvider(os.Getenv(resendAPIKeyEnvironment), nil)
		if providerErr != nil {
			fatal(providerErr)
		}
		if strings.TrimSpace(*confirmationFrom) == "" {
			fatal(errors.New("confirmation-from is required when signup is enabled"))
		}
		if _, parseErr := mail.ParseAddress(*confirmationFrom); parseErr != nil {
			fatal(errors.New("confirmation-from is invalid"))
		}
		if strings.TrimSpace(*confirmationReplyTo) != "" {
			if _, parseErr := mail.ParseAddress(*confirmationReplyTo); parseErr != nil {
				fatal(errors.New("confirmation-reply-to is invalid"))
			}
		}
		options.Signup = &subscriptions.SignupOptions{Config: subscriptions.SignupConfig{
			Audience: *signupAudience, ConsentSource: *consentSource, PrivacyNoticeVersion: *privacyVersion,
			PrivacyNoticeURL: *privacyURL, ConfirmationTTL: *confirmationTTL, DispatchCooldown: time.Minute, MaxPending: *maximumPending,
		}, Sender: resendConfirmationSender{provider: provider, from: *confirmationFrom, replyTo: *confirmationReplyTo}}
	}
	handler, err := registry.HandlerWithOptions(options)
	if err != nil {
		fatal(err)
	}
	server := &http.Server{
		Addr:              strings.TrimSpace(*listenAddress),
		Handler:           handler,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      10 * time.Second,
		IdleTimeout:       30 * time.Second,
		MaxHeaderBytes:    8 << 10,
		ErrorLog:          log.New(os.Stderr, "unsubscribe service: ", 0),
	}
	if server.Addr == "" {
		fatal(errors.New("listen address is required"))
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	done := make(chan error, 1)
	go func() {
		done <- server.ListenAndServe()
	}()
	fmt.Printf("subscription service listening (address=%s tls=reverse-proxy-required resend_webhook=%t signup=%t)\n", server.Addr, *enableResendWebhook, *enableSignup)

	select {
	case err := <-done:
		if !errors.Is(err, http.ErrServerClosed) {
			fatal(err)
		}
	case <-ctx.Done():
		shutdownContext, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := server.Shutdown(shutdownContext); err != nil {
			fatal(err)
		}
		if err := <-done; !errors.Is(err, http.ErrServerClosed) {
			fatal(err)
		}
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "unsubscribe service failed:", err)
	os.Exit(1)
}
